stages:
  - test
  - deploy

testing frontend:
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm test

testing backend:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm test

deploying to heroku:
  stage: deploy
  script:
    - dpl --provider=heroku --app=destdonation --api-key=$HEROKU_API_KEY
