stages:
  - test
  - production

testing frontend:
  stage: test
  script:
    - cd client
    - npm ci
    - npm run test:CI

testing backend:
  stage: test
  script:
    - npm ci
    - npm run test:CI

deploying to heroku:
  stage: production
  script:
    - dpl --provider=heroku --app=destdonation --api-key=$DESTDONATION_AUTH_TOKEN
  environment:
    name: Heroku
    url: https://destdonation.herokuapp.com/
