stages:
  - test
  - deploy

testing frontend:
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm test

testing backend:
  stage: test
  script:
    - cd backend
    - npm ci
    - npm test

deploying to heroku:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=destdonation --api-key=$heroku_api_key
